name: grocery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  get: ^4.6.5
  dio: ^5.1.2
  icons_plus: ^4.0.0
  flutter_svg: ^2.0.2
  connectivity_plus: ^4.0.1
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  share_plus: ^7.0.2
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
